bd:
  image: postgres
rabbit:
  image: rabbitmq
  ports:
   - "15672:15672"
   - "4369:4369"
   - "5671:5671"
   - "5672:5672"
   - "25672:25672"
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - bd
    - rabbit
